<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\EventJudgePanel;

class _BootstrapEventJudgePanelsSeeder extends Seeder
{
    public function run(): void
    {
        /**
         * ===============================
         * PILIH EVENT TARGET
         * ===============================
         * 👉 Ganti sesuai kebutuhan:
         * - event aktif
         * - event tertentu (by id)
         */

        $event = Event::query()
            ->orderByDesc('id')
            ->first();

        if (! $event) {
            $this->command->warn('⚠ Tidak ada event ditemukan. Seeder dibatalkan.');
            return;
        }

        /**
         * ===============================
         * GENERATE MAJELIS 1 - 10
         * ===============================
         */
        for ($i = 1; $i <= 10; $i++) {

            $name = 'Majelis Hakim ' . $i;
            $code = 'MJH-' . str_pad($i, 2, '0', STR_PAD_LEFT);

            EventJudgePanel::firstOrCreate(
                [
                    'event_id' => $event->id,
                    'name'     => $name, // 🔐 unik per event
                ],
                [
                    'code'      => $code,
                    'notes'     => 'Auto generated by seeder',
                    'is_active' => true,
                ]
            );
        }

        $this->command->info(
            "✔ 10 Majelis Hakim berhasil dibuat untuk event: {$event->name}"
        );
    }
}
